// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nocupseudwdtvjokliny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vY3Vwc2V1ZHdkdHZqb2tsaW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTA3MTgsImV4cCI6MjA2NTI4NjcxOH0.K4Yvwszu7ML3ZAnWUMZxHFckWmMiq370_QKrPeLROaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);